/**
 * Generate docs/ai-crawlers.md from the AI bot registry.
 * Usage: npx tsx scripts/gen-bots-doc.ts
 */
import { writeFileSync } from 'node:fs';
import { AI_BOTS, type AiBot } from '../src/core/bots.js';

const PURPOSE_LABELS: Record<AiBot['purpose'], string> = {
  search: 'Search & answer crawlers',
  'user-fetch': 'User-triggered fetchers',
  mixed: 'Mixed-purpose crawlers',
  training: 'Training crawlers',
};

const PURPOSE_ORDER: AiBot['purpose'][] = ['search', 'user-fetch', 'mixed', 'training'];

const ROBOTS_BADGE: Record<NonNullable<AiBot['robotsTxt']>, string> = {
  honored: '✅ honored',
  bypass: '⚠️ may bypass',
  unverified: '❔ unverified',
};

function row(bot: AiBot): string {
  const retired = bot.retired ? ` ~~retired~~ → \`${bot.replacedBy}\`` : '';
  const control = bot.controlOnly ? ' *(opt-out signal, not a crawler)*' : '';
  const docs = bot.docs ? `[docs](${bot.docs})` : '—';
  const notes = (bot.notes ?? '').replaceAll('|', '\\|');
  return `| \`${bot.id}\` | ${bot.company} | ${ROBOTS_BADGE[bot.robotsTxt ?? 'unverified']} | ${retired}${control} ${notes} ${docs} |`;
}

const active = AI_BOTS.filter((b) => !b.retired);
const lines: string[] = [
  '# AI crawler & fetcher reference',
  '',
  `A maintained registry of **${active.length} active AI bot tokens** (${AI_BOTS.length} including retired)`,
  'that site owners can control via `robots.txt` — the same data that powers',
  '`geolint bots`, the `list_ai_bots` MCP tool and every robots.txt audit.',
  '',
  '**Why purpose matters:** blocking a *search* or *user-fetch* bot makes your site',
  'invisible in AI answers **now**; blocking a *training* bot only affects future',
  'model data. *Control-only* tokens are opt-out signals, not crawlers.',
  '',
  '## Quick postures for robots.txt',
  '',
  '```txt',
  '# Allow AI search citations, opt out of training (recommended for most sites)',
  'User-agent: OAI-SearchBot',
  'Allow: /',
  'User-agent: ChatGPT-User',
  'Allow: /',
  'User-agent: GPTBot',
  'Disallow: /',
  '```',
  '',
  '```txt',
  '# Block every AI crawler & fetcher (control tokens excluded — they are not crawlers)',
  ...AI_BOTS.filter((b) => !b.retired && !b.controlOnly).map((b) => `User-agent: ${b.id}`),
  'Disallow: /',
  '```',
  '',
  'Run `npx @iliasabk/geolint bots` for the live list, or `check yoursite.com` to',
  'evaluate your own robots.txt against every token below.',
  '',
];

for (const purpose of PURPOSE_ORDER) {
  const bots = AI_BOTS.filter((b) => b.purpose === purpose && !b.retired && !b.controlOnly);
  if (bots.length === 0) continue;
  lines.push(
    `## ${PURPOSE_LABELS[purpose]} (${bots.length})`,
    '',
    purpose === 'search' || purpose === 'user-fetch'
      ? '> ⚠️ Blocking these removes your site from AI answers **immediately**.'
      : '',
    '| Token | Company | robots.txt | Notes |',
    '| --- | --- | --- | --- |',
    ...bots.map(row),
    '',
  );
}

const controlOnly = AI_BOTS.filter((b) => b.controlOnly && !b.retired);
if (controlOnly.length > 0) {
  lines.push(
    '## Opt-out control tokens',
    '',
    '> Not crawlers — they are signals vendors check before using your content.',
    '',
    '| Token | Company | robots.txt | Notes |',
    '| --- | --- | --- | --- |',
    ...controlOnly.map(row),
    '',
  );
}

const retired = AI_BOTS.filter((b) => b.retired);
if (retired.length > 0) {
  lines.push(
    '## Retired tokens',
    '',
    '> Still found in older robots.txt files — safe to replace with the successor.',
    '',
    '| Token | Company | robots.txt | Notes |',
    '| --- | --- | --- | --- |',
    ...retired.map(row),
    '',
  );
}

lines.push(
  '---',
  '',
  `_This file is generated by \`scripts/gen-bots-doc.ts\` from \`src/core/bots.ts\` (${AI_BOTS.length} tokens). Do not edit by hand._`,
  'Corrections welcome via issue or PR — please cite vendor documentation.',
  '',
);

writeFileSync(new URL('../docs/ai-crawlers.md', import.meta.url), lines.join('\n'));
console.log(`docs/ai-crawlers.md written (${AI_BOTS.length} tokens)`);
